### ISSUE TITLE
Middle clicking the last tab crashes the program

### ISSUE THREAD

**Issue by KianKhadempour** [derceg/explorerplusplus#413]
**Describe the bug**
Middle clicking (to close) the last tab crashes the program.

**To Reproduce**
1. Middle click (scroll wheel click) on the tab when there is only one open.
2. The program crashes.

**Expected behavior**
As with right-clicking and selecting "Close Tab" or pressing Ctrl+W, I expect the tab to stay there and not crash the program.

**Crashes**
Please attach the associated crash dump. This file should be created in %temp% and be named something like Explorer++1.4.0.0-11102020-194414.dmp. Not attaching a crash dump may make it significantly more difficult to diagnose the cause of a crash.

[Explorer++.exe.12636.dmp](https://github.com/derceg/explorerplusplus/files/13211159/Explorer%2B%2B.exe.12636.dmp)

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1748 beta (64-bit build)
 - Windows 10 Home 22H2

**Additional context**
I have just downloaded it so corruption shouldn't be a problem.

**Comment by derceg** [comment]
Thanks, this was fixed in 037c2b294de4ec63563f6a98f2497a8766c0263f.

**Comment by eduarddejong** [comment]
Sorry, just for my understanding, but why am I still experiencing this issue in the current version 1.4.0 from Jan 28?

**Comment by derceg** [comment]
@eduarddejong Version 1.4.0 is several years out of date, so this fix is in newer dev versions. I've been planning to release a beta for the next version at some point, so I'll likely do that in the near future. Going forward, the goal would be to reduce the difference between the dev/stable versions, so that the stable version lags only a little behind the dev version. That would then prevent confusing situations like this. Until then, the dev version is available.

**Comment by eduarddejong** [comment]
Thanks for clarifying! I see it now. The related commits are much older than the build.

Ok, so now I'm running this one:

Explorer++ version 1.5.0.2430 dev (64-bit build)
Build date: Jun 15 2024 00:13:21

Looks good. :)
But this version still has the middle click crash here. It's not a big deal though.

**Comment by derceg** [comment]
If the updated version is also crashing, please file a new bug, with the crash dump attached.

**Comment by derceg** [comment]
Alright, thanks for letting me know!
